version: '2'
services:
    peduc2-app:
        image: peduc2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://peduc2-postgresql:5432/peduc2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://peduc2-elasticsearch:9200
        ports:
            - 8080:8080
    peduc2-postgresql:
        extends:
            file: postgresql.yml
            service: peduc2-postgresql
    peduc2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: peduc2-elasticsearch
